#!/bin/sh

/home1/comparif/ror/comparifier/test/comparifier/current/script/process/spawner \
  mongrel \
  --environment=development \
  --instances=1 \
  --address=http://comparifier.com \
  --port=12008